export declare const rxp: {
    any: string;
    zeroMoreWhitespace: string;
    singleQuoteQuoted: string;
    doubleQuoteQuoted: string;
    jsonNameVluSep: string;
    beginString: string;
    jsonStart: string;
    jsonEnd: string;
    jsonStartArray: string;
    jsonStartObject: string;
    comma: string;
    or: string;
    beginCapture: string;
    closeParen: string;
    endCapture: string;
    endCaptureZeroOne: string;
    endCaptureZeroMore: string;
    endCaptureOneMore: string;
    oneMoreNumeric: string;
    oneMoreDigits: string;
    oneMoreAlpha: string;
    oneMoreName: string;
    oneMoreWord: string;
    oneMoreWhitespace: string;
    openParen: string;
    stringStart: string;
    stringEnd: string;
    variableName: string;
    zeroOneAny: string;
    zeroMoreWord: string;
    oneMoreAnyBut: (anyChars: string) => string;
    jsonVluStart: () => string;
    jsonPropName: () => string;
    jsonNameVluPair: () => string;
    escape: (char: string) => string;
};
