name: on_push

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: echo to artifact
      run: |
        echo Hello there! > steve.txt
      uses: actions/upload-artifact@v1
      with:
        name: messages
        path: steve.txt
      